### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by reedstrm** [waharnum/mathjax_d3-experiment#1]
Not really an issue, just wanted to communicate that this is an awesome quick demo. I was a participant at that sprint/hackfest, and your work gives me some ideas for extending mathmlcloud
for additional modalities. (I'm with openstax, BTW)

**Comment by waharnum** [comment]
Thanks @reedstrm - I discovered after posting it that it doesn't handle division gracefully due to its extremely naive parsing of MathML, but 3/4 arithmetic statements doesn't seem bad for the time put in. Glad it gave you some ideas!
